### ISSUE TITLE
zar OOM with increased -sortmem

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1297]
As #1203 was being worked on & merged, I'd asked some questions about its use and didn't get super clear answers. Specifically, I'd heard it said that the value for the `-sortmem` parameter could not be assumed to behave like a hard ceiling on the amount of consumed memory, and I'd been told of observations that the actual observed memory used by the process might be 2-3x the value. I wanted to have my own sense of comfort about the setting's expected behaviors since users might ask for guidance regarding its use. I therefore did some black box testing yesterday and the results were not good, as the `zar` process ran out of memory.

I forgot to write down the precise `zq` commit I was testing with (oops!) but it was one from September 15, 2020. I suspect it might have been `71e35ad`.

I was testing with a Google Cloud `n1-standard-16` instance, which has 60 GB of memory. I also provisioned it with one local SSD to hold test data and to use as `$TMPDIR` for spill space. In the spirit of the opening remarks of #974, I was taking on the persona of a user that assumed that some of the excess memory could surely be put to use in the interest of improving performance and reducing disk I/O.

My test used the full 70 GB wrccdc data set. First I ran a baseline that used minimal memory and did lots of spill-to-disk sorting:

```
$ time (zq *.log | zar import -s 25MB -)

real 98m33.796s
user 187m10.849s
sys 16m44.837s
```

During the run, I used Telegraf to poll for the RSS memory used by the `zar` process and charted it with Grafana. The usage:

![image](https://user-images.githubusercontent.com/5934157/93409437-c041e100-f84b-11ea-96ac-8b23d9ccb911.png)

Then for a test run, I increased `-sortmem` to 10 GiB. I picked this value on the assumption that the 2-3x fudge factor was legitimate, and hence this seemed like a conservative place to start from since even if 3x that amount were used, half of the system memory would still be left free. However in this case the `zar` process OOM'ed a little over 30 minutes into the run.

```
$ time (zq *.log | zar -sortmem 100000 import -s 25MB -)
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc92b7b, 0x16)
/usr/lib/go-1.15/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xcf48000000, 0xb4000000, 0x174a7f8)
/usr/lib/go-1.15/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x122ade0, 0xb3c00000, 0x42d8f7, 0x122ade8)
/usr/lib/go-1.15/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x122ade0, 0x59c76, 0x0)
/usr/lib/go-1.15/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x122ade0, 0x59c76, 0x7fd2c3350000, 0x174a808, 0xfffffffffffffade)
/usr/lib/go-1.15/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
/usr/lib/go-1.15/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x122ade0, 0x59c76, 0x460100, 0x122ade0)
/usr/lib/go-1.15/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0xb38ec000, 0x460001, 0xcf46351000)
/usr/lib/go-1.15/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
/usr/lib/go-1.15/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x0)
/usr/lib/go-1.15/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
/usr/lib/go-1.15/src/runtime/proc.go:1116

goroutine 55 [running]:
runtime.systemstack_switch()
/usr/lib/go-1.15/src/runtime/asm_amd64.s:330 fp=0xc000087d68 sp=0xc000087d60 pc=0x46d640
runtime.mallocgc(0xb38ec000, 0xc53580, 0x1, 0xcd08e10eb8)
/usr/lib/go-1.15/src/runtime/malloc.go:1070 +0x938 fp=0xc000087e08 sp=0xc000087d68 pc=0x40f958
runtime.growslice(0xc53580, 0xcc7aeb4000, 0x11f4ac00, 0x11f4ac00, 0x11f4ac01, 0xcc7aeb4000, 0xe5d5400, 0x11f4ac00)
/usr/lib/go-1.15/src/runtime/slice.go:230 +0x1e9 fp=0xc000087e70 sp=0xc000087e08 pc=0x450a29
github.com/brimsec/zq/proc/sort.(*Proc).recordsForOneRun(0xc000040400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/phil/zq/proc/sort/sort.go:119 +0x14c fp=0xc000087f30 sp=0xc000087e70 pc=0x97244c
github.com/brimsec/zq/proc/sort.(*Proc).sortLoop(0xc000040400)
/home/phil/zq/proc/sort/sort.go:63 +0x75 fp=0xc000087fd8 sp=0xc000087f30 pc=0x971d95
runtime.goexit()
/usr/lib/go-1.15/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000087fe0 sp=0xc000087fd8 pc=0x46f421
created by github.com/brimsec/zq/proc/sort.(*Proc).Pull.func1
/home/phil/zq/proc/sort/sort.go:50 +0x3e

goroutine 1 [select, 32 minutes]:
github.com/brimsec/zq/driver.(*muxOutput).Pull(0xc00014a140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/phil/zq/driver/mux.go:110 +0x1c5
github.com/brimsec/zq/driver.runMux(0xc00014a140, 0xdc6f20, 0xc00014a000, 0x0, 0xc00014a6e0, 0xdbea40)
/home/phil/zq/driver/driver.go:40 +0x8a
github.com/brimsec/zq/driver.MultiRun(0xdc6fe0, 0xc0002d8240, 0xdc6f20, 0xc00014a000, 0xdb7100, 0xc000521440, 0xc00014a6e0, 0xdbea40, 0xc000521590, 0x0, ...)
/home/phil/zq/driver/driver.go:35 +0x18d
github.com/brimsec/zq/driver.Run(0xdc6fe0, 0xc0002d8240, 0xdc6f20, 0xc00014a000, 0xdb7100, 0xc000521440, 0xc00014a6e0, 0xdb7400, 0xc0002d8150, 0x0, ...)
/home/phil/zq/driver/driver.go:24 +0x266
github.com/brimsec/zq/archive.Import(0xdc6fe0, 0xc0002d8240, 0xc0001f7a00, 0xc00014a6e0, 0xdb7400, 0xc0002d8150, 0x0, 0x0)
/home/phil/zq/archive/import.go:128 +0x16c
github.com/brimsec/zq/cmd/zar/import.(*Command).Run(0xc0002975e0, 0xc000138060, 0x1, 0x1, 0x0, 0x0)
/home/phil/zq/cmd/zar/import/command.go:107 +0x585
github.com/mccanne/charm.(*instance).run(0xc000129ac0, 0xc000138040, 0x3, 0x3, 0x0, 0x0)
/home/phil/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x293
github.com/mccanne/charm.(*Spec).Exec(0x11dd6e0, 0xdb72a0, 0xc00014a5a0, 0xc000138040, 0x3, 0x3, 0x4, 0x0)
/home/phil/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:67 +0x94
github.com/mccanne/charm.(*instance).run(0xc000129aa0, 0xc000138010, 0x6, 0x6, 0x0, 0x0)
/home/phil/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:61 +0x426
github.com/mccanne/charm.(*Spec).ExecRoot(0x11ddaa0, 0xc000138010, 0x6, 0x6, 0xc00021ff78, 0x407de5, 0xc00010e058, 0x0)
/home/phil/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
/home/phil/zq/cmd/zar/main.go:20 +0x85

goroutine 19 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293790)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 20 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293860)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 21 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293930)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 22 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293a00)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 23 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293ad0)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 24 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293ba0)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 25 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293c70)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 26 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293d40)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 27 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293e10)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 28 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000293ee0)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 29 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0002c8000)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 30 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0002c80d0)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 31 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0002c81a0)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 32 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0002c8270)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 33 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0002c8340)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 34 [chan receive, 32 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0002c8410)
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:195 +0x155
created by github.com/klauspost/compress/zstd.newBlockDec
/home/phil/go/pkg/mod/github.com/klauspost/compress@v1.10.3/zstd/blockdec.go:110 +0x173

goroutine 52 [syscall, 32 minutes]:
os/signal.signal_recv(0x0)
/usr/lib/go-1.15/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
/usr/lib/go-1.15/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
/usr/lib/go-1.15/src/os/signal/signal.go:150 +0x45

goroutine 53 [select, 32 minutes]:
github.com/brimsec/zq/pkg/signalctx.New.func1(0xc000098660, 0xc0002d8240, 0xc000294270, 0xdc6be0, 0xc0002d4480)
/home/phil/zq/pkg/signalctx/signalctx.go:25 +0xcf
created by github.com/brimsec/zq/pkg/signalctx.New
/home/phil/zq/pkg/signalctx/signalctx.go:24 +0x12f

goroutine 54 [chan receive, 32 minutes]:
github.com/brimsec/zq/proc/sort.(*Proc).Pull(0xc000040400, 0x0, 0x0, 0x0, 0x0)
/home/phil/zq/proc/sort/sort.go:51 +0x7a
github.com/brimsec/zq/driver.(*mux).safeGet(0xc000129a00, 0x0, 0x0, 0x0, 0x0)
/home/phil/zq/driver/mux.go:52 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc000129a00)
/home/phil/zq/driver/mux.go:65 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
/home/phil/zq/driver/mux.go:103 +0x5d

goroutine 57 [chan receive, 32 minutes]:
github.com/brimsec/zq/driver.(*parallelHead).closeOnDone(0xc00014a0f0)
/home/phil/zq/driver/parallel.go:26 +0x51
created by github.com/brimsec/zq/driver.(*parallelHead).Pull.func2
/home/phil/zq/driver/parallel.go:42 +0x3e

real 32m37.262s
user 79m35.015s
sys 7m27.432s
```

The RSS memory usage ramp:

![image](https://user-images.githubusercontent.com/5934157/93409640-29c1ef80-f84c-11ea-8910-b0bda0b3ceb4.png)

All that said, I do see that the observed RSS in the run without increasing `-sortmem` didn't exactly stay "flat", so it seems plausible that the issue is somehow fundamental to how memory is allocated/used and not unique to increased `-sortmem`, though clearly the increased value is aggregating it.

**Comment by philrz** [comment]
@nwt pointed out that I had an extra `0` in my `-sortmem 100000`. Boy do I feel stupid! I'll re-run the test and post results that confirm it was all my mistake, and hopefully close this as a dumb tangent. Sorry for the false alarm folks!

**Comment by philrz** [comment]
As predicted, the OOM was due to my mistake. I'll be closing this one as "invalid".

Here's the results from a re-run with `zar` commit `2608a46`. With the proper 10 MiB setting, the operation completed in a little over 95 minutes, with a flat-ish memory peak period and an absolute peak at 30.8 GiB, indicating a 3x fudge factor relative to the my requested 10,000 MiB limit.

```
# time (zq *.log.gz | zar -sortmem 10000 import -s 25MB -)

real    95m40.528s
user    173m3.706s
sys     14m23.569s
```

![image](https://user-images.githubusercontent.com/5934157/93546490-b4235580-f917-11ea-8b81-8b515b239a15.png)

The CPU chart showing relative CPU usage between `zq` and `zar` shows an interesting pattern, apparently due to the spill-to-disk sorting happening in 10 GB increments.

![image](https://user-images.githubusercontent.com/5934157/93546533-cdc49d00-f917-11ea-9e51-54a1505d0d50.png)

```
# while true; do   du -sh zq-sort-*;   sleep 60; done
4.0K	zq-sort-183956291
4.0K	zq-sort-183956291
7.2G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
10G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
20G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
30G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
43G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
50G	zq-sort-183956291
40G	zq-sort-183956291
40G	zq-sort-183956291
```

For the comparative baseline without increased `-sortmem`, we observe the low/flat memory curve, and also see validation of something @marktwallace had observed: It actually took slightly _less_ time and consumed slightly _less_ CPU by using less memory and relying on spill-to-disk in these smaller increments.

```
# time (zq *.log.gz | zar import -s 25MB -)

real    92m59.811s
user    160m50.622s
sys     13m34.865s
```

![image](https://user-images.githubusercontent.com/5934157/93546654-1f6d2780-f918-11ea-8863-5d2da427e4ee.png)

![image](https://user-images.githubusercontent.com/5934157/93546661-23994500-f918-11ea-987b-b6bed297bfd2.png)

```
# while true; do   du -sh zq-sort-*;   sleep 60; done
132M	zq-sort-646119493
657M	zq-sort-646119493
1.2G	zq-sort-646119493
1.8G	zq-sort-646119493
2.4G	zq-sort-646119493
3.0G	zq-sort-646119493
3.6G	zq-sort-646119493
4.4G	zq-sort-646119493
5.0G	zq-sort-646119493
5.7G	zq-sort-646119493
6.2G	zq-sort-646119493
6.8G	zq-sort-646119493
7.5G	zq-sort-646119493
8.4G	zq-sort-646119493
8.7G	zq-sort-646119493
9.4G	zq-sort-646119493
9.9G	zq-sort-646119493
11G	zq-sort-646119493
11G	zq-sort-646119493
12G	zq-sort-646119493
12G	zq-sort-646119493
13G	zq-sort-646119493
14G	zq-sort-646119493
14G	zq-sort-646119493
15G	zq-sort-646119493
16G	zq-sort-646119493
16G	zq-sort-646119493
17G	zq-sort-646119493
18G	zq-sort-646119493
19G	zq-sort-646119493
19G	zq-sort-646119493
20G	zq-sort-646119493
20G	zq-sort-646119493
21G	zq-sort-646119493
21G	zq-sort-646119493
22G	zq-sort-646119493
22G	zq-sort-646119493
23G	zq-sort-646119493
24G	zq-sort-646119493
24G	zq-sort-646119493
25G	zq-sort-646119493
25G	zq-sort-646119493
25G	zq-sort-646119493
26G	zq-sort-646119493
26G	zq-sort-646119493
27G	zq-sort-646119493
28G	zq-sort-646119493
28G	zq-sort-646119493
29G	zq-sort-646119493
29G	zq-sort-646119493
30G	zq-sort-646119493
30G	zq-sort-646119493
31G	zq-sort-646119493
32G	zq-sort-646119493
32G	zq-sort-646119493
33G	zq-sort-646119493
34G	zq-sort-646119493
34G	zq-sort-646119493
35G	zq-sort-646119493
35G	zq-sort-646119493
36G	zq-sort-646119493
36G	zq-sort-646119493
37G	zq-sort-646119493
37G	zq-sort-646119493
38G	zq-sort-646119493
38G	zq-sort-646119493
39G	zq-sort-646119493
40G	zq-sort-646119493
40G	zq-sort-646119493
41G	zq-sort-646119493
42G	zq-sort-646119493
42G	zq-sort-646119493
43G	zq-sort-646119493
44G	zq-sort-646119493
44G	zq-sort-646119493
45G	zq-sort-646119493
46G	zq-sort-646119493
47G	zq-sort-646119493
47G	zq-sort-646119493
48G	zq-sort-646119493
48G	zq-sort-646119493
49G	zq-sort-646119493
49G	zq-sort-646119493
50G	zq-sort-646119493
50G	zq-sort-646119493
48G	zq-sort-646119493
39G	zq-sort-646119493
34G	zq-sort-646119493
29G	zq-sort-646119493
23G	zq-sort-646119493
17G	zq-sort-646119493
12G	zq-sort-646119493
5.2G	zq-sort-646119493
```

We may want to further investigate these effects, but for now, my OOM claim is now confirmed to have been a false alarm. Apologies to @nwt!
