### ISSUE TITLE
"panic: interface conversion" when doing "zapi help create" or "zapi help find"

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1332]
I was trying to verify #882 and hence working at `zq` commit `2bbd3c9`, which is the commit for linked PR #1289. I tried to look at the help text and got a panic.

```
$ zapi help create
panic: interface conversion: charm.Command is *cmd.Command, not *idx.IndexCmd

goroutine 1 [running]:
github.com/brimsec/zq/cmd/zapi/cmd/index.NewCreate(0x1b2f700, 0xc0003ec080, 0xc0003f6120, 0xc0003f6120, 0x6, 0xc00029fc01, 0x2)
	/Users/phil/work/zq/cmd/zapi/cmd/index/create.go:56 +0x27a
github.com/mccanne/charm.newInstance(0x1b2f700, 0xc0003ec080, 0x20e4300, 0x20e4300, 0x1, 0x7ffeefbffaaa)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:19 +0x74
github.com/mccanne/charm.(*HelpCommand).search(0xc0003f2004, 0xc0000321d0, 0x1, 0x1, 0x0, 0x100eac8, 0x0, 0xc00006c800, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/help.go:74 +0x1e7
github.com/mccanne/charm.(*HelpCommand).Run(0xc0003f2004, 0xc0000321d0, 0x1, 0x1, 0xc0000321d0, 0x1)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/help.go:87 +0x4d
github.com/mccanne/charm.(*instance).run(0xc0003f4020, 0xc0000321d0, 0x1, 0x1, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x28c
github.com/mccanne/charm.(*Spec).Exec(0x20e4a80, 0x1b2f700, 0xc0003ec000, 0xc0000321d0, 0x1, 0x1, 0x2, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:67 +0x92
github.com/mccanne/charm.(*instance).run(0xc0003f4000, 0xc0000321c0, 0x2, 0x2, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:61 +0x41d
github.com/mccanne/charm.(*Spec).ExecRoot(0x20e41c0, 0xc0000321c0, 0x2, 0x2, 0xc00029ff78, 0x100763f, 0xc00009c058, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
	/Users/phil/work/zq/cmd/zapi/main.go:20 +0x78
```

I see a similar panic when I do `zapi help find`.

**Comment by philrz** [comment]
Verified in `zapi` commit `51a0a44`.

The `create` and `find` options are now gone from the top-level set of commands, hence no more way to make it panic.

```
$ zapi -version
Version: v0.22.0-53-g51a0a44

$ zapi help
NAME
    zapi - use zapi to talk to a zqd server

USAGE
    zapi [global options] command [options] [arguments...]

OPTIONS
    -cpuprofile write cpu profile to given file name
    -h <host[:port]> (default "localhost:9867")
    -id <space_id>
    -memprofile write memory profile to given file name
    -nofancy disable fancy CLI output (true if stdout is not a tty) (default "false")
    -s <space>
    -version print version and exit (default "false")

COMMANDS
    help - display help for a command
    get - perform zql searches
    index - query and create search indexes
    info - show information about a space
    ls - list spaces or information about a space
    new - create a new space
    newsubspace - create a new subspace
    pcappost - post a pcap file to a space
    post - post log file(s) to a space
    rename - renames a space
    repl - enter read-eval-print loop
    rm - removes a space
    version - show version of connected zqd

DESCRIPTION
    The zapi command-line tool is used to talk to a zq analytics service.
    This service could be zqd running on your laptop or in the cloud.

    Zapi is prounounced "zappy".

    With zapi you can create spaces, list spaces, post data to spaces, and
    run queries.

    The Brim application and the zapi client use the same REST API for
    interacting with a zq analytics service.

$ zapi find
zapi: no such sub-command: find

$ zapi create
zapi: no such sub-command: create

$ zapi help find
no such command: find

$ zapi help create
no such command: create
```

Thanks @mattnibs!
