### ISSUE TITLE
SEGV when attempting to query non-existent index

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1419]
Repro is with `zar` commit `ccbfade`.

If I seed the archive as shown in the  [`zar` README](https://github.com/brimsec/zq/blob/master/cmd/zar/README.md), but then attempt to query the index before creating it, I get as SEGV rather than an error message.

```
$ zq zng/*.gz | zar import -s 25MB -
$ zar find :ip=10.10.23.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16c65b6]

goroutine 55 [running]:
github.com/brimsec/zq/microindex.(*Reader).Path(...)
	/Users/phil/work/zq/microindex/reader.go:134
github.com/brimsec/zq/archive.search(0x1ac9b60, 0xc0000b43c0, 0xc00009a320, 0xc00010e720, 0xc0000364e0, 0x4, 0x0, 0x0, 0x0, 0xc0000364e7, ...)
	/Users/phil/work/zq/archive/finder.go:129 +0x1a6
github.com/brimsec/zq/archive.Find.func2.1(0xc00010e720, 0xab5c41b8751c080c, 0x33d7f41a86710e79, 0xcdeaa9ef, 0x151eebcd15773fb0, 0x151eeb5da84c7438, 0x188e245, 0x1, 0x6fa8a, 0xc00015a8c0, ...)
	/Users/phil/work/zq/archive/finder.go:102 +0x1f6
created by github.com/brimsec/zq/archive.Find.func2
	/Users/phil/work/zq/archive/finder.go:99 +0x1aa
```

**Comment by philrz** [comment]
Verified in `zar` commit `c0204bc`.

Now instead of the SEGV panic, we get an error message.

```
$ zq zng/*.gz | zar import -s 25MB -
$ zar find :ip=10.10.23.2
file:///Users/phil/logs/zd/20180324/d-1if3MWnfccER5ph4cswE3gZgxCi.zng.zar/microindex-type-ip.zng: item does not exist: file:///Users/phil/logs/zd/20180324/d-1if3MWnfccER5ph4cswE3gZgxCi.zng.zar/microindex-type-ip.zng
```

It does seem like we might improve this error message at some point, but, mission accomplished on not crashing. 😄 

Thanks @alfred-landrum!
