### ISSUE TITLE
Crash when "zapi post -f" is used and the Space already exists

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1443]
A community user stumbled into this while working with `zapi` to prepare for some remote `zqd` use cases. I've since reproduced the symptom using current `zqd` and `zapi` at commit `f5d679d`.

Start a listening `zqd` in an empty directory:

```
$ zqd -version
Version: v0.22.0-27-gf5d679d

$ zqd listen
{"level":"info","ts":1602180429.026339,"msg":"Starting","datadir":".","open_files_limit":24576,"pprof_routes":false,"suricata_supported":false,"zeek_supported":false}
{"level":"info","ts":1602180429.026829,"logger":"httpd","msg":"Listening","addr":"[::]:9867"}
...
```

Post a log while forcing Space creation (using the [zq-sample-data Zeek weird log](https://github.com/brimsec/zq-sample-data/blob/master/zeek-default/weird.log.gz) in this case).

```
$ zapi -s My_Test post -f weird.log.gz 
100.0% 316.2KB/316.2KB
posted 316.2KB in 129.815797ms
```

If I repeat the exact same command line, there's a crash:

```
$ zapi -s My_Test post -f weird.log.gz 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1741c6a]

goroutine 1 [running]:
github.com/brimsec/zq/cmd/zapi/cmd/post.(*LogCommand).Run(0xc000332080, 0xc000032290, 0x1, 0x1, 0xc000032290, 0x1)
	/Users/phil/work/zq/cmd/zapi/cmd/post/post.go:60 +0x89a
github.com/mccanne/charm.(*instance).run(0xc00000eec0, 0xc000032280, 0x2, 0x2, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x28c
github.com/mccanne/charm.(*Spec).Exec(0x210ac60, 0x1b46be0, 0xc000326400, 0xc000032280, 0x2, 0x2, 0x3, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:67 +0x92
github.com/mccanne/charm.(*instance).run(0xc00000eea0, 0xc000032250, 0x5, 0x5, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:61 +0x41d
github.com/mccanne/charm.(*Spec).ExecRoot(0x210a620, 0xc000032250, 0x5, 0x5, 0xc000317f78, 0x100763f, 0xc00010a058, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
	/Users/phil/work/zq/cmd/zapi/main.go:21 +0x78
```

Without the `-f`, it works fine, replacing the contents of the Space. I know this is all due to change since we're going to need to support adding data to an existing Space. But since it's a crash, reporting it anyway.

**Comment by mattnibs** [comment]
Will be fixed when https://github.com/brimsec/zq/pull/1336 merges

**Comment by philrz** [comment]
Thanks @mattnibs. I'll put this one in your name for now, then, and will verify when it gets closed.

**Comment by philrz** [comment]
Verified in `zq` commit `9bcc81b`.

The repeated log post with `-f` no longer triggers a crash.

```
$ zqd -version
Version: v0.23.0-15-g9bcc81b

$ zqd listen
{"level":"info","ts":1605285214.196723,"msg":"Starting","datadir":".","open_files_limit":24576,"pprof_routes":false,"suricata_supported":false,"zeek_supported":false}
{"level":"info","ts":1605285214.1974888,"logger":"httpd","msg":"Listening","addr":"[::]:9867"}
...
```

```
$ zapi -s My_Test post -f weird.log.gz
posted 316.2KB in 103.514812ms

$ zapi -s My_Test post -f weird.log.gz
posted 316.2KB in 113.207703ms
```

Thanks @mattnibs!
