### ISSUE TITLE
zar zq: concurrent map read/write panic for bare word search

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1589]
Steps to reproduce:
1. Import wrccdc-year1 data set into a new zar folder: `zar import -R scratch /path/to/data/*.log`
2. Run any bare word search on data: `zar zq -R scratch "google | count()"

Observe that zar zq ends with panic:

```
fatal error: concurrent map read and map write
fatal error: concurrent map read and map write

goroutine 36 [running]:
runtime.throw(0x1a4ee36, 0x21)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc000072bd0 sp=0xc000072ba0 pc=0x1035c92
runtime.mapaccess2(0x1911aa0, 0xc0003608d0, 0xc000072c90, 0x295e7ceedfac78d0, 0xc000072cb8)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/map.go:469 +0x258 fp=0xc000072c10 sp=0xc000072bd0 pc=0x10102a8
github.com/brimsec/zq/filter.searchRecordString.func1(0xc000840028, 0x1a26fbe)
	/Users/nibs/Code/zq/filter/filter.go:183 +0x97 fp=0xc000072cc8 sp=0xc000072c10 pc=0x15d53d7
github.com/brimsec/zq/zio/zngio.(*zngScanner).scanOne(0xc000840000, 0xc000840028, 0xc000840028, 0x0, 0x0)
	/Users/nibs/Code/zq/zio/zngio/scanner.go:131 +0xe9 fp=0xc000072d18 sp=0xc000072cc8 pc=0x15e4cc9
github.com/brimsec/zq/zio/zngio.(*zngScanner).scanBatch(0xc000840000, 0xc00007be50, 0xc00007be50, 0x1, 0x1c873c0)
	/Users/nibs/Code/zq/zio/zngio/scanner.go:117 +0x133 fp=0xc000072dc8 sp=0xc000072d18 pc=0x15e4883
github.com/brimsec/zq/zio/zngio.(*zngScanner).Pull(0xc000840000, 0x1ca1d20, 0xc000618f30, 0x0, 0x0)
	/Users/nibs/Code/zq/zio/zngio/scanner.go:44 +0x3b3 fp=0xc000072e88 sp=0xc000072dc8 pc=0x15e4613
github.com/brimsec/zq/ppl/archive.(*scannerCloser).Pull(0xc000838020, 0x3, 0xc000618f30, 0x0, 0xc000072f08)
	<autogenerated>:1 +0x3c fp=0xc000072ec0 sp=0xc000072e88 pc=0x181e96c
github.com/brimsec/zq/driver.(*parallelHead).Pull(0xc000109770, 0x0, 0x0, 0x0, 0x0)
	/Users/nibs/Code/zq/driver/parallel.go:72 +0xea fp=0xc000072f40 sp=0xc000072ec0 pc=0x17e656a
github.com/brimsec/zq/proc/groupby.(*Proc).run(0xc00037e300)
	/Users/nibs/Code/zq/proc/groupby/groupby.go:228 +0x154 fp=0xc000072fd8 sp=0xc000072f40 pc=0x1652754
runtime.goexit()
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000072fe0 sp=0xc000072fd8 pc=0x1066d31
created by github.com/brimsec/zq/proc/groupby.(*Proc).Pull.func1
	/Users/nibs/Code/zq/proc/groupby/groupby.go:215 +0x3e
```

**Comment by philrz** [comment]
Verified in `zar` commit `3954f31`.

I first witnessed the repro using `zar` commit `645d67d` that came right before the change in the linked PR.

```
$ echo $ZAR_ROOT
/Users/phil/logs

$ zar -version
Version: v0.23.0-4-g645d67d

$ zar import *.log
$ zar zq -t "google | count()"
fatal error: concurrent map read and map write

goroutine 82 [running]:
runtime.throw(0x1929caf, 0x21)
	/usr/local/opt/go/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc00007bbd0 sp=0xc00007bba0 pc=0x1038732
runtime.mapaccess2(0x18022a0, 0xc000a5e150, 0xc00007bc90, 0x295e8b2386dd0920, 0xc00007bcb8)
...
```

Now on `zar` commit `3954f31` that has the fix in the linked PR:

```
$ zar -version
Version: v0.23.0-5-g3954f31

$ zar import *.log
$ zar zq -t "google | count()"
#0:record[count:uint64]
0:[518711;]
```

Thanks @mattnibs!
