### ISSUE TITLE
compiler panic with `cut(.)`

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1931]
```
11:31 ~/work/brim/zq(shaping-functions)
$ zq -t "put a=cut(.)" all.zng 

panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/brimsec/zq/zng/builder.NewColumnBuilder(0xc00028df40, 0xc0003a80a0, 0x1, 0x1, 0xf, 0x0, 0x0)
        /Users/henridf/work/brim/zq/zng/builder/colbuilder.go:97 +0x9ba
github.com/brimsec/zq/expr.NewCutter(0xc00028df40, 0xc0003a80a0, 0x1, 0x1, 0xc0002e80a0, 0x1, 0x1, 0xf, 0x0, 0x0)
        /Users/henridf/work/brim/zq/expr/cutter.go:33 +0x50
github.com/brimsec/zq/compiler.compileCutter(0xc00028df40, 0x18ca115, 0xc, 0xc0002d33c0, 0x3, 0xc0002e8f50, 0x1, 0x1, 0x170, 0x8a4087ac145c319c, ...)
        /Users/henridf/work/brim/zq/compiler/expr.go:261 +0x388
github.com/brimsec/zq/compiler.compileCall(0xc00028df40, 0x18ca115, 0xc, 0xc0002d33c0, 0x3, 0xc0002e8f50, 0x1, 0x1, 0x2d1d600, 0x20300000000000, ...)
        /Users/henridf/work/brim/zq/compiler/expr.go:292 +0x6f1
github.com/brimsec/zq/compiler.CompileExpr(0xc00028df40, 0x1a034e0, 0xc00028dd80, 0x28, 0x28, 0x27867d0, 0xc0002f00f0)
        /Users/henridf/work/brim/zq/compiler/expr.go:59 +0x547
github.com/brimsec/zq/compiler.CompileAssignment(0xc00028df40, 0xc00079f228, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100, 0x2efffff)
        /Users/henridf/work/brim/zq/compiler/expr.go:194 +0x79
github.com/brimsec/zq/compiler.compileAssignments(0xc0002f04b0, 0x1, 0x1, 0xc00028df40, 0x203000, 0x8, 0x2000, 0x203000, 0x203000)
        /Users/henridf/work/brim/zq/compiler/proc.go:210 +0x127
github.com/brimsec/zq/compiler.compileProc(0x0, 0x1a03700, 0xc0002f04e0, 0xc0002f00c0, 0x1a0bf40, 0xc0002e8090, 0xa, 0x1a03380, 0xc00028dd40, 0x1a034e0)
        /Users/henridf/work/brim/zq/compiler/proc.go:146 +0x657
github.com/brimsec/zq/compiler.Compile(0x0, 0x1a03700, 0xc0002f04e0, 0xc0002f00c0, 0xc0002e8070, 0x1, 0x1, 0x0, 0x100000002, 0x203000, ...)
        /Users/henridf/work/brim/zq/compiler/proc.go:333 +0x585
github.com/brimsec/zq/compiler.compileSequential(0x0, 0xc0002e8f30, 0x1, 0x1, 0xc0002f00c0, 0xc0002e8070, 0x1, 0x1, 0x100f690, 0xc0002f00c0, ...)
        /Users/henridf/work/brim/zq/compiler/proc.go:240 +0xb4
github.com/brimsec/zq/compiler.Compile(0x0, 0x1a037c0, 0xc0002f0510, 0xc0002f00c0, 0xc0002e8070, 0x1, 0x1, 0x7fffffffffffffff, 0x1a0c900, 0xc00029d0e0, ...)
        /Users/henridf/work/brim/zq/compiler/proc.go:301 +0x737
github.com/brimsec/zq/driver.compile(0x1a14140, 0xc000394100, 0x1a037c0, 0xc0002f0510, 0xc00028df40, 0xc00079fac8, 0x1, 0x1, 0x0, 0xc00010e240, ...)
        /Users/henridf/work/brim/zq/driver/compile.go:77 +0x545
github.com/brimsec/zq/driver.Run(0x1a14700, 0xc000710060, 0x1a14440, 0xc0002f0060, 0x1a037c0, 0xc0002f0510, 0xc00028df40, 0x1a04100, 0xc000710030, 0x0, ...)
        /Users/henridf/work/brim/zq/driver/driver.go:29 +0x145
main.(*Command).Run(0xc000296c00, 0xc0000320e0, 0x2, 0x2, 0x0, 0x0)
        /Users/henridf/work/brim/zq/cmd/zq/zq.go:180 +0x9b5
github.com/mccanne/charm.(*instance).run(0xc00000fc20, 0xc0000320d0, 0x3, 0x3, 0x0, 0x0)
        /Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x293
github.com/mccanne/charm.(*Spec).ExecRoot(0x1e53d00, 0xc0000320d0, 0x3, 0x3, 0xc00019ff78, 0x1007f65, 0xc00008e058, 0x0)
        /Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
        /Users/henridf/work/brim/zq/cmd/zq/main.go:9 +0x85
```

**Comment by henridf** [comment]
Similarly when using `cut` as a proc:

```
$ zq -t "cut .=id" input.tzng 
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/brimsec/zq/zng/builder.NewColumnBuilder(0xc0002cb100, 0xc00030e080, 0x1, 0x1, 0x1a094c0, 0xc00030e060, 0x23c09f0)
	/Users/henridf/work/brim/zq/zng/builder/colbuilder.go:97 +0x9ba
github.com/brimsec/zq/expr.NewCutter(0xc0002cb100, 0xc00030e080, 0x1, 0x1, 0xc0003100a0, 0x1, 0x1, 0x1, 0x1, 0x10)
	/Users/henridf/work/brim/zq/expr/cutter.go:33 +0x50
github.com/brimsec/zq/compiler.compileProc(0x0, 0x1a08dc0, 0xc0002e7b90, 0xc0003120c0, 0x1a11820, 0xc000310090, 0x400, 0x2c18e00, 0x20300000000000, 0x2dfffff)
	/Users/henridf/work/brim/zq/compiler/proc.go:66 +0x234d
github.com/brimsec/zq/compiler.Compile(0x0, 0x1a08dc0, 0xc0002e7b90, 0xc0003120c0, 0xc000310070, 0x1, 0x1, 0x0, 0x0, 0x64, ...)
	/Users/henridf/work/brim/zq/compiler/proc.go:333 +0x585
github.com/brimsec/zq/compiler.compileSequential(0x0, 0xc0002db6c0, 0x1, 0x1, 0xc0003120c0, 0xc000310070, 0x1, 0x1, 0x100f690, 0xc0003120c0, ...)
	/Users/henridf/work/brim/zq/compiler/proc.go:240 +0xb4
github.com/brimsec/zq/compiler.Compile(0x0, 0x1a09140, 0xc0002e7bc0, 0xc0003120c0, 0xc000310070, 0x1, 0x1, 0x7fffffffffffffff, 0x1a11f60, 0xc0003080c0, ...)
	/Users/henridf/work/brim/zq/compiler/proc.go:301 +0x737
github.com/brimsec/zq/driver.compile(0x1a19a20, 0xc000314000, 0x1a09140, 0xc0002e7bc0, 0xc0002cb100, 0xc00021fac8, 0x1, 0x1, 0x0, 0xc000308060, ...)
	/Users/henridf/work/brim/zq/driver/compile.go:77 +0x545
github.com/brimsec/zq/driver.Run(0x1a19fe0, 0xc0002e7ec0, 0x1a19d20, 0xc000312060, 0x1a09140, 0xc0002e7bc0, 0xc0002cb100, 0x1a099e0, 0xc0002e7e90, 0x0, ...)
	/Users/henridf/work/brim/zq/driver/driver.go:29 +0x145
main.(*Command).Run(0xc000103980, 0xc000138020, 0x2, 0x2, 0x0, 0x0)
	/Users/henridf/work/brim/zq/cmd/zq/zq.go:180 +0x9b5
github.com/mccanne/charm.(*instance).run(0xc000129ca0, 0xc000138010, 0x3, 0x3, 0x0, 0x0)
	/Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x293
github.com/mccanne/charm.(*Spec).ExecRoot(0x1e5ad20, 0xc000138010, 0x3, 0x3, 0xc00021ff78, 0x1007f65, 0xc00010e058, 0x0)
	/Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
	/Users/henridf/work/brim/zq/cmd/zq/main.go:9 +0x85
```

**Comment by philrz** [comment]
Verified in `zq` commit `871df67c`.

As it turns out, as of `zq` commit `45fa6d3b` that was right before the changes were merged from the linked PR, these were no longer panics. Instead we seemed to catch & disallow them. Using an `all.zng` based on having imported https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz into Brim:

```
$ zq -t "put a=cut(.)" all.zng
rhs of assigment expression: root field

$ zq -t "cut .=id" all.zng 
root field
```

Now with current `zq` at commit `871df67c`, we get actual results.

```
$ zq -t "put a=cut(.)" all.zng
#0:record[_path:string,ts:time,ts_delta:duration,peer:bstring,gaps:uint64,acks:uint64,percent_lost:float64,a:record[_path:string,ts:time,ts_delta:duration,peer:bstring,gaps:uint64,acks:uint64,percent_lost:float64]]
0:[capture_loss;1521835214.3314;111.694792;zeek;15;72667;0.020642;[capture_loss;1521835214.3314;111.694792;zeek;15;72667;0.020642;]]
#1:record[_path:string,ts:time,peer:bstring,mem:uint64,pkts_proc:uint64,bytes_recv:uint64,pkts_dropped:uint64,pkts_link:uint64,pkt_lag:duration,events_proc:uint64,events_queued:uint64,active_tcp_conns:uint64,active_udp_conns:uint64,active_icmp_conns:uint64,tcp_conns:uint64,udp_conns:uint64,icmp_conns:uint64,timers:uint64,active_timers:uint64,files:uint64,active_files:uint64,dns_requests:uint64,active_dns_requests:uint64,reassem_tcp_size:uint64,reassem_file_size:uint64,reassem_frag_size:uint64,reassem_unknown_size:uint64,a:record[_path:string,ts:time,peer:bstring,mem:uint64,pkts_proc:uint64,bytes_recv:uint64,pkts_dropped:uint64,pkts_link:uint64,pkt_lag:duration,events_proc:uint64,events_queued:uint64,active_tcp_conns:uint64,active_udp_conns:uint64,active_icmp_conns:uint64,tcp_conns:uint64,udp_conns:uint64,icmp_conns:uint64,timers:uint64,active_timers:uint64,files:uint64,active_files:uint64,dns_requests:uint64,active_dns_requests:uint64,reassem_tcp_size:uint64,reassem_file_size:uint64,reassem_frag_size:uint64,reassem_unknown_size:uint64]]
1:[stats;1521835214.3314;zeek;519;1650918;473585160;-;-;-;1060403;1060403;29135;87;1446;392651;1453;1447;1217499;0;4155;6;15;0;64425;0;0;0;[stats;1521835214.3314;zeek;519;1650918;473585160;-;-;-;1060403;1060403;29135;87;1446;392651;1453;1447;1217499;0;4155;6;15;0;64425;0;0;0;]]
...

$ zq -t "_path=conn | cut .=id" all.zng
#port=uint16
#0:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port]
0:[10.236.58.83;45264;10.47.1.30;16833;]
0:[10.236.58.83;40474;10.47.1.55;16840;]
...
```

Incidentally, when running the _precise_ repro step that lacked the `_path=conn`, it actually happens to fail with this data because the first record encountered in the `all.zng` happens to lack the `id` field, so this happens:

```
$ zq -t "cut .=id" all.zng
field is not present
```

Now that I see it, I imagine we might want to rethink how we handle this case, but I'll take it up as a separate topic.

Thanks @nwt!
