### ISSUE TITLE
Panic from attempted access of array element in "by" grouping

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#2139]
Repro is with `zq` commit `0dba379a`.

Let's say I've got a `null` string in my input. If I try to access it like an array with `put`, I get a helpful error message.

```
$ echo '{"mynull": null}' | zq -f zson 'put a=mynull[0]' -
cannot index type "string" with key "int64: ()"
{
    mynull: null (string)
} (=0)
```

However, if I attempt a similar access in a `by` grouping of an aggregation, I get a panic.

```
$ echo '{"mynull": null}' | zq -f zson 'count() by a=mynull[0]' -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x155d814]

goroutine 69 [running]:
github.com/brimsec/zq/zng/resolver.recordKey(0xc000a12400, 0x2, 0x2, 0x5, 0xc000717c10)
	/Users/phil/work/zq/zng/resolver/context.go:125 +0xb4
github.com/brimsec/zq/zng/resolver.(*Context).LookupTypeRecord(0xc00061e4c0, 0xc000a12400, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/zng/resolver/context.go:228 +0x1ac
github.com/brimsec/zq/proc/groupby.(*Aggregator).lookupRecordType(0xc0000e2120, 0xc00060ec80, 0x2, 0x2, 0xc000036100, 0x1, 0x8)
	/Users/phil/work/zq/proc/groupby/groupby.go:554 +0x114
github.com/brimsec/zq/proc/groupby.(*Aggregator).readTable(0xc0000e2120, 0xc000600001, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/groupby/groupby.go:525 +0x49b
github.com/brimsec/zq/proc/groupby.(*Aggregator).Results(0xc0000e2120, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/groupby/groupby.go:359 +0xde
github.com/brimsec/zq/proc/groupby.(*Proc).run(0xc000a12300)
	/Users/phil/work/zq/proc/groupby/groupby.go:178 +0x354
created by github.com/brimsec/zq/proc/groupby.(*Proc).Pull.func1
	/Users/phil/work/zq/proc/groupby/groupby.go:158 +0x3e
```

**Comment by philrz** [comment]
Verified in `zq` commit 7c7abe9.

The first example above now returns a more helpful error message.

```
$ zq -version
Version: v0.29.0-109-g7c7abe91

$ echo '{"mynull": null}' | zq -f zson 'put a=mynull[0]' -
put: a referenced field is missing
{
    mynull: null (null)
} (=0)
```

The second no longer panics and instead gives the expected lack of output that one expects for having counted nothing:

```
$ echo '{"mynull": null}' | zq -f zson 'count() by a=mynull[0]' -
[no output]
```

Thanks @henridf!
