### ISSUE TITLE
type bindings need to be evaluated incrementally in compileConsts

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2198]
This doesn't work:
```
type port=uint16;
type conn={orig_h:ip,orig_p:port,resp_h:ip,resp_p:port};
put . = shape(., {_path:string,ts:time,uid:bstring,id:conn})
```

**Comment by philrz** [comment]
My attempt to verify this one in current `zq` commit `82630a52` has failed.

In `zq` commit `120d08dc` that pre-dated the changes in the linked PR, it's correct that the example showed in the opening text did not work, returning an error message.

```
$ echo '{"foo": "bar"}' | zq -f zson -I example.zs -
no such type name: "port"

$ zq -version
Version: v0.29.0-57-g120d08dc

$ cat example.zs 
type port=uint16;
type conn={orig_h:ip,orig_p:port,resp_h:ip,resp_p:port};
put . = shape(., {_path:string,ts:time,uid:bstring,id:conn})
11:27:27-phil@PhilMac:~/work/zq-2198$ echo '{"foo": "bar"}' | zq -f zson -I example.zs -
no such type name: "port"
```

Now at current `zq` commit `82630a52` it instead fails with a panic.

```
$ zq -version
Version: v0.29.0-62-g82630a52

$ echo '{"foo": "bar"}' | zq -f zson -I example.zs -
panic: interface conversion: zng.Type is *zng.TypeAlias, not *zng.TypeRecord
goroutine 8 [running]:
runtime/debug.Stack(0x46, 0x40, 0x6b)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/brimsec/zq/zqe.RecoverError(0x182e980, 0xc00034be90, 0xc00034be90, 0xc0000ce400)
	/Users/phil/work/zq/zqe/error.go:163 +0x26
github.com/brimsec/zq/driver.(*mux).safeGet.func1(0xc00001bf70)
	/Users/phil/work/zq/driver/mux.go:49 +0x48
panic(0x182e980, 0xc00034be90)
	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
github.com/brimsec/zq/expr.(*Shaper).orderRecordType(0xc000033440, 0xc00034bb00, 0xc00034bb00, 0xc00034bb00, 0x0, 0x0)
	/Users/phil/work/zq/expr/shaper.go:404 +0xa10
github.com/brimsec/zq/expr.(*Shaper).createShapeSpec(0xc000033440, 0xc00034bda0, 0xc00034bb00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/phil/work/zq/expr/shaper.go:323 +0x1ee
github.com/brimsec/zq/expr.(*Shaper).Eval(0xc000033440, 0xc000514500, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000514501, 0xc00050cc40)
	/Users/phil/work/zq/expr/shaper.go:285 +0x337
github.com/brimsec/zq/proc/put.(*Proc).eval(0xc0005134d0, 0xc000514500, 0x0, 0xc00050cc40, 0xc00001bd98, 0x15b87dc, 0xc00050caa0)
	/Users/phil/work/zq/proc/put/put.go:84 +0x127
github.com/brimsec/zq/proc/put.(*Proc).put(0xc0005134d0, 0xc000514500, 0xc000514500, 0xc0000c07d8, 0x0)
	/Users/phil/work/zq/proc/put/put.go:347 +0x50
github.com/brimsec/zq/proc/put.(*Proc).Pull(0xc0005134d0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/put/put.go:371 +0x15f
github.com/brimsec/zq/driver.(*mux).safeGet(0xc00050cb00, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:51 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc00050cb00)
	/Users/phil/work/zq/driver/mux.go:64 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
	/Users/phil/work/zq/driver/mux.go:98 +0x5d
```

#2219 has been opened to track this as a bug.
