### ISSUE TITLE
Shapers don't handle aliases to different castable types

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#2279]
In #2257 we added for handling aliases/typedefs, but that support does not extend to aliases to different types. 

For example: 

`echo '{a: 1 (myport=(int16))}' | type port=int64; put .=cast({a:port})`

fails due to int16 vs 64.

**Comment by philrz** [comment]
Verified in `zq` commit f93774d.

Circling back to `zq` commit d715606 that was right before the changes in the linked PR, it was a panic.

```
$ zq -version
Version: v0.29.0-90-gd7156066

$ echo '{a: 1 (myport=(int16))}' | zq -z 'type port=int64; put .=cast({a:port})' -
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
runtime/debug.Stack(0x246f600, 0xc000414440, 0xc00042e360)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/brimsec/zq/zqe.RecoverError(0x1833040, 0x1edf2c0, 0x1edf2c0, 0x203000)
	/Users/phil/work/zq/zqe/error.go:163 +0x26
github.com/brimsec/zq/driver.(*mux).safeGet.func1(0xc00044bf70)
	/Users/phil/work/zq/driver/mux.go:49 +0x48
panic(0x1833040, 0x1edf2c0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
github.com/brimsec/zq/expr.(*step).castPrimitive(0xc00044ba10, 0xc00042e32a, 0x1, 0x6, 0xc000426128)
	/Users/phil/work/zq/expr/shaper.go:148 +0x119
github.com/brimsec/zq/expr.(*step).build(0xc00044ba10, 0xc00042e32a, 0x1, 0x6, 0xc000426128)
	/Users/phil/work/zq/expr/shaper.go:163 +0x93
github.com/brimsec/zq/expr.(*step).buildRecord(0xc00044bb88, 0xc00042e329, 0x2, 0x7, 0xc000426128)
	/Users/phil/work/zq/expr/shaper.go:212 +0x22f
github.com/brimsec/zq/expr.(*Shaper).Eval(0xc000426120, 0xc00041a1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00041a101, 0xc000412420)
	/Users/phil/work/zq/expr/shaper.go:299 +0x246
github.com/brimsec/zq/proc/put.(*Proc).eval(0xc000420240, 0xc00041a1e0, 0x0, 0xc000412420, 0xc00044bd98, 0x15b9edc, 0xc0004121e0)
	/Users/phil/work/zq/proc/put/put.go:84 +0x127
github.com/brimsec/zq/proc/put.(*Proc).put(0xc000420240, 0xc00041a1e0, 0xc00041a1e0, 0xc00041c078, 0x0)
	/Users/phil/work/zq/proc/put/put.go:347 +0x50
github.com/brimsec/zq/proc/put.(*Proc).Pull(0xc000420240, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/put/put.go:371 +0x15f
github.com/brimsec/zq/driver.(*mux).safeGet(0xc0004122a0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:51 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc0004122a0)
	/Users/phil/work/zq/driver/mux.go:64 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
	/Users/phil/work/zq/driver/mux.go:98 +0x5d
```

But it works in `zq` commit f93774d.

```
$ zq -version
Version: v0.29.0-94-gf93774d0
14:18:40-phil@PhilMac:~/work/zq-2279$ echo '{a: 1 (myport=(int16))}' | zq -z 'type port=int64; put .=cast({a:port})' -
{a:1 (=port)} (=0)
```
