### ISSUE TITLE
Inferred json reader crashes on multiple nested fields

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#747]
I noticed this while working on #714.

```
$ echo '{"a.b.c": 1, "a.b.d": 2}' | zq -t -
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/brimsec/zq/zio/ndjsonio.(*inferParser).parseObject(0xc000032608, 0xc000342000, 0x18, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, ...)
        /Users/henridf/work/brim/zq/zio/ndjsonio/inferparser.go:62 +0xe2c
github.com/brimsec/zq/zio/ndjsonio.(*Reader).Parse(0xc000032600, 0xc000342000, 0x18, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00003c090, ...)
        /Users/henridf/work/brim/zq/zio/ndjsonio/reader.go:112 +0x184
github.com/brimsec/zq/zio/ndjsonio.(*Reader).Read(0xc000032600, 0x13d9f42, 0x18f8ce0, 0xc00003c090)
        /Users/henridf/work/brim/zq/zio/ndjsonio/reader.go:126 +0xac
github.com/brimsec/zq/zio/detector.match(0x1b903c0, 0xc000032600, 0x195f8a4, 0x6, 0x0, 0x0)
        /Users/henridf/work/brim/zq/zio/detector/reader.go:70 +0x38
github.com/brimsec/zq/zio/detector.NewReader(0x1b90340, 0xc0002fb200, 0xc0002e2540, 0xc0002fb200, 0xc0000be000, 0x0, 0x1)
        /Users/henridf/work/brim/zq/zio/detector/reader.go:49 +0x588
github.com/brimsec/zq/zio/detector.OpenFromNamedReadCloser(0xc0002e2540, 0x1b99b20, 0xc0000be000, 0x7ffeefbffa86, 0x1, 0x195d3d9, 0x4, 0x1, 0x0, 0x1998ef3, ...)
        /Users/henridf/work/brim/zq/zio/detector/file.go:131 +0xaf
github.com/brimsec/zq/zio/detector.OpenFile(0xc0002e2540, 0x7ffeefbffa86, 0x1, 0x195d3d9, 0x4, 0x1, 0x0, 0x1998ef3, 0x59, 0x0, ...)
        /Users/henridf/work/brim/zq/zio/detector/file.go:68 +0x11a
main.(*Command).inputReaders(0xc0002e40a0, 0xc0000ce050, 0x1, 0x1, 0x0, 0x0, 0xaa00000001927a60, 0x1115f01, 0xaa7e7729fbbf34ca)
        /Users/henridf/work/brim/zq/cmd/zq/zq.go:270 +0x166
main.(*Command).Run(0xc0002e40a0, 0xc0000ce050, 0x1, 0x1, 0x0, 0x0)
        /Users/henridf/work/brim/zq/cmd/zq/zq.go:218 +0x2cf
github.com/mccanne/charm.(*instance).run(0xc0000ede20, 0xc0000ce040, 0x2, 0x2, 0x0, 0x0)
        /Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x28c
github.com/mccanne/charm.(*Spec).ExecRoot(0x2155000, 0xc0000ce040, 0x2, 0x2, 0xc0002cdf50, 0x100742f, 0xc0000a6058, 0x0)
        /Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
        /Users/henridf/work/brim/zq/cmd/zq/main.go:9 +0x78
```

**Comment by philrz** [comment]
![image](https://user-images.githubusercontent.com/5934157/81479903-19817000-91db-11ea-8782-cf24f916ecf2.png)

**Comment by philrz** [comment]
Verified in `zq` commit `de55ba7`. This no longer crashes:

```
$ echo '{"a.b.c": 1, "a.b.d": 2}' | zq -t -
#0:record[a:record[b:record[c:float64,d:float64]]]
0:[[[1;2;]]]
```

Thanks @nwt!
