### ISSUE TITLE
Panic when trying to concatenate string and numeric values

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#934]
Repro is with `zq` commit `3af5a8e`.

In an expression, concatenating two strings works without complaint:

```
$ echo '{"str1": "foo", "str2": "bar", "num": 2}' | zq -t 'put text=str1+str2' -
#0:record[num:float64,str1:string,str2:string,text:string]
0:[2;foo;bar;foobar;]
```

However if I try to concatenate a string and a number, we get a panic.

```
$ echo '{"str1": "foo", "str2": "bar", "num": 2}' | zq -t 'put text=str1+num' -
panic: interface conversion: interface {} is float64, not string
goroutine 31 [running]:
runtime/debug.Stack(0x118d04d, 0xc0000f3848, 0xc0000ed801)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/brimsec/zq/zqe.RecoverError(0x17141c0, 0xc0002e1350, 0xc0002e1350, 0x8)
	/Users/phil/work/zq/zqe/error.go:124 +0x26
github.com/brimsec/zq/driver.(*Mux).safeGet.func1(0xc0000f3f70)
	/Users/phil/work/zq/driver/mux.go:46 +0x48
panic(0x17141c0, 0xc0002e1350)
	/usr/local/opt/go/libexec/src/runtime/panic.go:967 +0x15d
github.com/brimsec/zq/expr.compileArithmetic.func1(0xc0002e1320, 0x0, 0xc0000f3bd8, 0x1318227, 0x19fc5a0, 0xc0000a8050, 0xc0000a8050)
	/Users/phil/work/zq/expr/expr.go:772 +0x1528
github.com/brimsec/zq/expr.CompileExpr.func1(0xc0002e1320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002e1320)
	/Users/phil/work/zq/expr/expr.go:48 +0x63
github.com/brimsec/zq/proc.(*Put).put(0xc0000c3aa0, 0xc0002e1320, 0xc0002e1320)
	/Users/phil/work/zq/proc/put.go:81 +0x183
github.com/brimsec/zq/proc.(*Put).Pull(0xc0000c3aa0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/put.go:232 +0x13b
github.com/brimsec/zq/proc.(*Base).Get(...)
	/Users/phil/work/zq/proc/proc.go:73
github.com/brimsec/zq/driver.(*Mux).safeGet(0xc0002e1200, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:48 +0x6d
github.com/brimsec/zq/driver.(*Mux).run(0xc0002e1200)
	/Users/phil/work/zq/driver/mux.go:61 +0x32
created by github.com/brimsec/zq/driver.(*MuxOutput).Pull.func1
	/Users/phil/work/zq/driver/mux.go:100 +0x5d
```

The panic message is actually pretty useful in this case, but in general we want to avoid sending stack dumps to the user.

**Comment by philrz** [comment]
I can verify that this was fixed in `zq` commit `56ed80d` that's associated with #1375. It no longer panics and instead provides an error message.

```
$ echo '{"str1": "foo", "str2": "bar", "num": 2}' | zq -t 'put text=str1+num' -
incompatible types
#0:record[num:float64,str1:string,str2:string]
0:[2;foo;bar;]
```

This error message seems to line up with the "type coercion rules" currently being drafted in https://github.com/brimsec/zq/issues/1408:

> ... a "plus" applied to a string and another type is a type mismatch and casts or conversion functions should be used.

Of course, if this record had been a single instance in a huge sea of non-mismatched records, the single error message in this case may not have given the user much to go on in narrowing down the root cause, and I believe @mccanne has ideas in progress for how to deliver context with errors, and that's being tracked separately.

Thanks @mccanne!
